import * as dotenv from 'dotenv';
dotenv.config();

const DEFAULT_HOST = 'localhost';

// Since all services are consolidated, they all use the same business service port
const BUSINESS_PORT = Number(process.env.BUSINESS_SERVICE_PORT ?? 5020);

export const envConfig = {
  // Business service (consolidated)
  BUSINESS_SERVICE_HOST: process.env.BUSINESS_SERVICE_HOST ?? DEFAULT_HOST,
  BUSINESS_SERVICE_PORT: BUSINESS_PORT,
  BUSINESS_SERVICE_HTTP_PORT: Number(process.env.BUSINESS_SERVICE_HTTP_PORT ?? 6020),

  // Legacy service references (all point to consolidated business service for backward compatibility)
  AUTH_SERVICE_HOST: process.env.BUSINESS_SERVICE_HOST ?? DEFAULT_HOST,
  AUTH_SERVICE_PORT: BUSINESS_PORT,
  CLUSTER_SERVICE_HOST: process.env.BUSINESS_SERVICE_HOST ?? DEFAULT_HOST,
  CLUSTER_SERVICE_PORT: BUSINESS_PORT,
  MASTER_SERVICE_HOST: process.env.BUSINESS_SERVICE_HOST ?? DEFAULT_HOST,
  MASTER_SERVICE_PORT: BUSINESS_PORT,
  INVENTORY_SERVICE_HOST: process.env.BUSINESS_SERVICE_HOST ?? DEFAULT_HOST,
  INVENTORY_SERVICE_PORT: BUSINESS_PORT,
  PROCUREMENT_SERVICE_HOST: process.env.BUSINESS_SERVICE_HOST ?? DEFAULT_HOST,
  PROCUREMENT_SERVICE_PORT: BUSINESS_PORT,
  NOTIFICATION_SERVICE_HOST: process.env.BUSINESS_SERVICE_HOST ?? DEFAULT_HOST,
  NOTIFICATION_SERVICE_PORT: BUSINESS_PORT,
  LOG_SERVICE_HOST: process.env.BUSINESS_SERVICE_HOST ?? DEFAULT_HOST,
  LOG_SERVICE_PORT: BUSINESS_PORT,

  // External services (services not consolidated into micro-business)
  KEYCLOAK_API_SERVICE_HOST: process.env.KEYCLOAK_API_SERVICE_HOST ?? DEFAULT_HOST,
  KEYCLOAK_API_SERVICE_PORT: Number(process.env.KEYCLOAK_API_SERVICE_PORT ?? 5013),
  FILE_SERVICE_HOST: process.env.FILE_SERVICE_HOST ?? DEFAULT_HOST,
  FILE_SERVICE_PORT: Number(process.env.FILE_SERVICE_PORT ?? 5007),
  REPORT_SERVICE_HOST: process.env.REPORT_SERVICE_HOST ?? DEFAULT_HOST,
  REPORT_SERVICE_PORT: Number(process.env.REPORT_SERVICE_PORT ?? 5004),
  CRONJOB_SERVICE_HOST: process.env.CRONJOB_SERVICE_HOST ?? DEFAULT_HOST,
  CRONJOB_SERVICE_PORT: Number(process.env.CRONJOB_SERVICE_PORT ?? 5012),

  // JWT configuration
  SUPABASE_JWT_SECRET: process.env.SUPABASE_JWT_SECRET ?? 'secret',
  JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN ?? '1d',
  JWT_REFRESH_EXPIRES_IN: process.env.JWT_REFRESH_EXPIRES_IN ?? '7d',
  JWT_INVITE_EXPIRES_IN: process.env.JWT_INVITE_EXPIRES_IN ?? '1d',

  // Database
  SYSTEM_DATABASE_URL: process.env.SYSTEM_DATABASE_URL,
  SYSTEM_DIRECT_URL: process.env.SYSTEM_DIRECT_URL,
};
