import { z } from 'zod';

const datetimeField = z.string().datetime().nullable();

// ==================== Transfer Detail Response ====================
export const TransferDetailResponseSchema = z.object({
  id: z.string().uuid(),
  tr_no: z.string().nullable(),
  tr_date: datetimeField,
  description: z.string().nullable(),
  doc_status: z.string().nullable(),
  from_location_id: z.string().uuid().nullable(),
  from_location_code: z.string().nullable(),
  from_location_name: z.string().nullable(),
  to_location_id: z.string().uuid().nullable(),
  to_location_code: z.string().nullable(),
  to_location_name: z.string().nullable(),
  // workflow_id: z.string().uuid().nullable(),
  // workflow_name: z.string().nullable(),
  // workflow_history: z.any().nullable(),
  // workflow_current_stage: z.string().nullable(),
  // workflow_previous_stage: z.string().nullable(),
  // workflow_next_stage: z.string().nullable(),
  // user_action: z.any().nullable(),
  // last_action: z.string().nullable(),
  // last_action_at_date: datetimeField,
  // last_action_by_id: z.string().uuid().nullable(),
  // last_action_by_name: z.string().nullable(),
  note: z.string().nullable(),
  info: z.any().nullable(),
  dimension: z.any().nullable(),
  doc_version: z.number().nullable(),
  created_at: datetimeField,
  created_by_id: z.string().uuid().nullable(),
  updated_at: datetimeField,
  updated_by_id: z.string().uuid().nullable(),
  tb_transfer_detail: z.array(z.any()).nullable(),
});

// ==================== Transfer List Item Response ====================
export const TransferListItemResponseSchema = z.object({
  id: z.string().uuid(),
  tr_no: z.string().nullable(),
  tr_date: datetimeField,
  description: z.string().nullable(),
  doc_status: z.string().nullable(),
  from_location_id: z.string().uuid().nullable(),
  from_location_code: z.string().nullable(),
  from_location_name: z.string().nullable(),
  to_location_id: z.string().uuid().nullable(),
  to_location_code: z.string().nullable(),
  to_location_name: z.string().nullable(),
  // workflow_id: z.string().uuid().nullable(),
  // workflow_name: z.string().nullable(),
  // workflow_current_stage: z.string().nullable(),
  // last_action: z.string().nullable(),
  // last_action_at_date: datetimeField,
  // last_action_by_name: z.string().nullable(),
  note: z.string().nullable(),
  created_at: datetimeField,
  created_by_id: z.string().uuid().nullable(),
  updated_at: datetimeField,
});

// ==================== Transfer Mutation Response ====================
export const TransferMutationResponseSchema = z.object({
  id: z.string().uuid(),
  tr_no: z.string().nullable(),
  tr_date: datetimeField,
  description: z.string().nullable(),
  doc_status: z.string().nullable(),
  from_location_id: z.string().uuid().nullable(),
  from_location_code: z.string().nullable(),
  from_location_name: z.string().nullable(),
  to_location_id: z.string().uuid().nullable(),
  to_location_code: z.string().nullable(),
  to_location_name: z.string().nullable(),
  created_at: datetimeField,
  updated_at: datetimeField,
});
