export interface ICreateRecipeEquipment {
  code: string;
  name: string;
  description?: string | null;
  category_id?: string | null;
  brand?: string | null;
  model?: string | null;
  serial_no?: string | null;
  capacity?: string | null;
  power_rating?: string | null;
  station?: string | null;
  operation_instructions?: string | null;
  safety_notes?: string | null;
  cleaning_instructions?: string | null;
  maintenance_schedule?: string | null;
  last_maintenance_date?: string | Date | null;
  next_maintenance_date?: string | Date | null;
  note?: string | null;
  is_active?: boolean;
  is_portable?: boolean;
  available_qty?: number;
  total_qty?: number;
  usage_count?: number;
  average_usage_time?: number;
  attachments?: unknown[];
  manuals_urls?: string[];
  info?: Record<string, unknown> | null;
  dimension?: unknown[] | null;
}

export interface IUpdateRecipeEquipment {
  id: string;
  code?: string;
  name?: string;
  description?: string | null;
  category_id?: string | null;
  brand?: string | null;
  model?: string | null;
  serial_no?: string | null;
  capacity?: string | null;
  power_rating?: string | null;
  station?: string | null;
  operation_instructions?: string | null;
  safety_notes?: string | null;
  cleaning_instructions?: string | null;
  maintenance_schedule?: string | null;
  last_maintenance_date?: string | Date | null;
  next_maintenance_date?: string | Date | null;
  note?: string | null;
  is_active?: boolean;
  is_portable?: boolean;
  available_qty?: number;
  total_qty?: number;
  usage_count?: number;
  average_usage_time?: number;
  attachments?: unknown[];
  manuals_urls?: string[];
  info?: Record<string, unknown> | null;
  dimension?: unknown[] | null;
}
