apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-gateway
  namespace: carmen-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-gateway
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: micro-business
  namespace: carmen-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: micro-business
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: micro-cluster
  namespace: carmen-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: micro-cluster
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: micro-keycloak-api
  namespace: carmen-backend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: micro-keycloak-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
