import * as dotenv from 'dotenv';
dotenv.config();

const DEFAULT_HOST = 'localhost';
const DEFAULT_PORTS = {
  GATEWAY: 4000,
  GATEWAY_HTTPS: 4001,
  AUTH: 5001,
  CLUSTER: 5002,
  LICENSE: 5003,
  REPORT: 5004,
  NOTIFICATION: 5006,
  FILE: 5007,
  TENANT_INVENTORY: 5008,
  TENANT_PROCUREMENT: 5009,
  TENANT_RECIPE: 5010,
  TENANT_MASTER: 5011,
  CRONJOB: 5012,
  KEYCLOAK_API: 5013,
  LOG: 5014,
};

export const envConfig = {
  GATEWAY_SERVICE_HOST: process.env.GATEWAY_SERVICE_HOST ?? DEFAULT_HOST,
  GATEWAY_SERVICE_PORT: Number(
    process.env.GATEWAY_SERVICE_PORT ?? DEFAULT_PORTS.GATEWAY,
  ),
  GATEWAY_SERVICE_HTTPS_PORT: Number(
    process.env.GATEWAY_SERVICE_HTTPS_PORT ?? DEFAULT_PORTS.GATEWAY_HTTPS,
  ),

  AUTH_SERVICE_HOST: process.env.AUTH_SERVICE_HOST ?? DEFAULT_HOST,
  AUTH_SERVICE_PORT: Number(
    process.env.AUTH_SERVICE_PORT ?? DEFAULT_PORTS.AUTH,
  ),
  AUTH_SERVICE_HTTP_PORT: Number(process.env.AUTH_SERVICE_HTTP_PORT ?? 6001),

  CLUSTER_SERVICE_HOST: process.env.CLUSTER_SERVICE_HOST ?? DEFAULT_HOST,
  CLUSTER_SERVICE_PORT: Number(
    process.env.CLUSTER_SERVICE_PORT ?? DEFAULT_PORTS.CLUSTER,
  ),
  CLUSTER_SERVICE_HTTP_PORT: Number(
    process.env.CLUSTER_SERVICE_HTTP_PORT ?? 6002,
  ),

  LICENSE_SERVICE_HOST: process.env.LICENSE_SERVICE_HOST ?? DEFAULT_HOST,
  LICENSE_SERVICE_PORT: Number(
    process.env.LICENSE_SERVICE_PORT ?? DEFAULT_PORTS.LICENSE,
  ),
  LICENSE_SERVICE_HTTP_PORT: Number(
    process.env.LICENSE_SERVICE_HTTP_PORT ?? 6003,
  ),

  REPORT_SERVICE_HOST: process.env.REPORT_SERVICE_HOST ?? DEFAULT_HOST,
  REPORT_SERVICE_PORT: Number(
    process.env.REPORT_SERVICE_PORT ?? DEFAULT_PORTS.REPORT,
  ),
  REPORT_SERVICE_HTTP_PORT: Number(
    process.env.REPORT_SERVICE_HTTP_PORT ?? 6004,
  ),

  NOTIFICATION_SERVICE_HOST:
    process.env.NOTIFICATION_SERVICE_HOST ?? DEFAULT_HOST,
  NOTIFICATION_SERVICE_PORT: Number(
    process.env.NOTIFICATION_SERVICE_PORT ?? DEFAULT_PORTS.NOTIFICATION,
  ),
  NOTIFICATION_SERVICE_HTTP_PORT: Number(
    process.env.NOTIFICATION_SERVICE_HTTP_PORT ?? 6006,
  ),

  FILE_SERVICE_HOST: process.env.FILE_SERVICE_HOST ?? DEFAULT_HOST,
  FILE_SERVICE_PORT: Number(
    process.env.FILE_SERVICE_PORT ?? DEFAULT_PORTS.FILE,
  ),
  FILE_SERVICE_HTTP_PORT: Number(process.env.FILE_SERVICE_HTTP_PORT ?? 6007),

  INVENTORY_SERVICE_HOST: process.env.INVENTORY_SERVICE_HOST ?? DEFAULT_HOST,
  INVENTORY_SERVICE_PORT: Number(
    process.env.INVENTORY_SERVICE_PORT ?? DEFAULT_PORTS.TENANT_INVENTORY,
  ),
  INVENTORY_SERVICE_HTTP_PORT: Number(
    process.env.INVENTORY_SERVICE_HTTP_PORT ?? 6008,
  ),

  PROCUREMENT_SERVICE_HOST:
    process.env.PROCUREMENT_SERVICE_HOST ?? DEFAULT_HOST,
  PROCUREMENT_SERVICE_PORT: Number(
    process.env.PROCUREMENT_SERVICE_PORT ?? DEFAULT_PORTS.TENANT_PROCUREMENT,
  ),
  PROCUREMENT_SERVICE_HTTP_PORT: Number(
    process.env.PROCUREMENT_SERVICE_HTTP_PORT ?? 6009,
  ),

  RECIPE_SERVICE_HOST: process.env.RECIPE_SERVICE_HOST ?? DEFAULT_HOST,
  RECIPE_SERVICE_PORT: Number(
    process.env.RECIPE_SERVICE_PORT ?? DEFAULT_PORTS.TENANT_RECIPE,
  ),
  RECIPE_SERVICE_HTTP_PORT: Number(
    process.env.RECIPE_SERVICE_HTTP_PORT ?? 6010,
  ),

  MASTER_SERVICE_HOST: process.env.MASTER_SERVICE_HOST ?? DEFAULT_HOST,
  MASTER_SERVICE_PORT: Number(
    process.env.MASTER_SERVICE_PORT ?? DEFAULT_PORTS.TENANT_MASTER,
  ),
  MASTER_SERVICE_HTTP_PORT: Number(
    process.env.MASTER_SERVICE_HTTP_PORT ?? 6011,
  ),

  CRONJOB_SERVICE_HOST: process.env.CRONJOB_SERVICE_HOST ?? DEFAULT_HOST,
  CRONJOB_SERVICE_PORT: Number(
    process.env.CRONJOB_SERVICE_PORT ?? DEFAULT_PORTS.CRONJOB,
  ),
  CRONJOB_SERVICE_HTTP_PORT: Number(
    process.env.CRONJOB_SERVICE_HTTP_PORT ?? 6012,
  ),

  KEYCLOAK_API_SERVICE_HOST:
    process.env.KEYCLOAK_API_SERVICE_HOST ?? DEFAULT_HOST,
  KEYCLOAK_API_SERVICE_PORT: Number(
    process.env.KEYCLOAK_API_SERVICE_PORT ?? DEFAULT_PORTS.KEYCLOAK_API,
  ),

  LOG_SERVICE_HOST: process.env.LOG_SERVICE_HOST ?? DEFAULT_HOST,
  LOG_SERVICE_PORT: Number(
    process.env.LOG_SERVICE_PORT ?? DEFAULT_PORTS.LOG,
  ),
  LOG_SERVICE_HTTP_PORT: Number(process.env.LOG_SERVICE_HTTP_PORT ?? 6014),

  IS_ACTIVE_NOTIFICATION: Boolean(process.env.IS_ACTIVE_NOTIFICATION),

  SUPABASE_JWT_SECRET: process.env.SUPABASE_JWT_SECRET,
};
