import { z } from 'zod';
import { createZodDto } from 'nestjs-zod';
import { enum_recipe_difficulty, enum_recipe_status } from '@repo/prisma-shared-schema-tenant';
import { AuditSchema } from '@/common/dto/audit/audit.dto';

export const RecipeCreate = z.object({
  code: z.string().min(1),
  name: z.string().min(1),
  description: z.string().nullable().optional(),
  note: z.string().nullable().optional(),
  is_active: z.boolean().default(true).optional(),
  images: z.any().optional(),
  category_id: z.string().uuid(),
  cuisine_id: z.string().uuid(),
  difficulty: z.enum(Object.values(enum_recipe_difficulty) as [string, ...string[]]).default('MEDIUM').optional(),
  base_yield: z.number(),
  base_yield_unit: z.string().min(1),
  default_variant_id: z.string().uuid().nullable().optional(),
  prep_time: z.number().int().optional(),
  cook_time: z.number().int().optional(),
  total_ingredient_cost: z.number().optional(),
  labor_cost: z.number().optional(),
  overhead_cost: z.number().optional(),
  cost_per_portion: z.number().optional(),
  suggested_price: z.number().nullable().optional(),
  selling_price: z.number().nullable().optional(),
  target_food_cost_percentage: z.number().nullable().optional(),
  actual_food_cost_percentage: z.number().nullable().optional(),
  gross_margin: z.number().nullable().optional(),
  gross_margin_percentage: z.number().nullable().optional(),
  labor_cost_percentage: z.number().nullable().optional(),
  overhead_percentage: z.number().nullable().optional(),
  carbon_footprint: z.number().nullable().optional(),
  deduct_from_stock: z.boolean().default(true).optional(),
  status: z.enum(Object.values(enum_recipe_status) as [string, ...string[]]).default('DRAFT').optional(),
  tags: z.any().optional(),
  allergens: z.any().optional(),
});

export type ICreateRecipe = z.infer<typeof RecipeCreate>;
export class RecipeCreateDto extends createZodDto(RecipeCreate) {}

export const RecipeUpdate = z.object({
  code: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  description: z.string().nullable().optional(),
  note: z.string().nullable().optional(),
  is_active: z.boolean().optional(),
  images: z.any().optional(),
  category_id: z.string().uuid().optional(),
  cuisine_id: z.string().uuid().optional(),
  difficulty: z.enum(Object.values(enum_recipe_difficulty) as [string, ...string[]]).optional(),
  base_yield: z.number().optional(),
  base_yield_unit: z.string().min(1).optional(),
  default_variant_id: z.string().uuid().nullable().optional(),
  prep_time: z.number().int().optional(),
  cook_time: z.number().int().optional(),
  total_ingredient_cost: z.number().optional(),
  labor_cost: z.number().optional(),
  overhead_cost: z.number().optional(),
  cost_per_portion: z.number().optional(),
  suggested_price: z.number().nullable().optional(),
  selling_price: z.number().nullable().optional(),
  target_food_cost_percentage: z.number().nullable().optional(),
  actual_food_cost_percentage: z.number().nullable().optional(),
  gross_margin: z.number().nullable().optional(),
  gross_margin_percentage: z.number().nullable().optional(),
  labor_cost_percentage: z.number().nullable().optional(),
  overhead_percentage: z.number().nullable().optional(),
  carbon_footprint: z.number().nullable().optional(),
  deduct_from_stock: z.boolean().optional(),
  status: z.enum(Object.values(enum_recipe_status) as [string, ...string[]]).optional(),
  tags: z.any().optional(),
  allergens: z.any().optional(),
});

export type IUpdateRecipe = z.infer<typeof RecipeUpdate> & { id: string };
export class RecipeUpdateDto extends createZodDto(RecipeUpdate) {}

export const RecipeResponseSchema = z.object({
  id: z.string().uuid(),
  code: z.string(),
  name: z.string(),
  description: z.string().nullable().optional(),
  note: z.string().nullable().optional(),
  is_active: z.boolean().nullable().optional(),
  images: z.any().optional(),
  category_id: z.string().uuid(),
  cuisine_id: z.string().uuid(),
  category: z.object({ id: z.string().uuid(), name: z.string(), code: z.string().optional() }).nullable().optional(),
  cuisine: z.object({ id: z.string().uuid(), name: z.string(), region: z.string().optional() }).nullable().optional(),
  difficulty: z.enum(Object.values(enum_recipe_difficulty) as [string, ...string[]]),
  base_yield: z.number(),
  base_yield_unit: z.string(),
  default_variant_id: z.string().uuid().nullable().optional(),
  prep_time: z.number(),
  cook_time: z.number(),
  total_ingredient_cost: z.number(),
  labor_cost: z.number(),
  overhead_cost: z.number(),
  cost_per_portion: z.number(),
  suggested_price: z.number().nullable().optional(),
  selling_price: z.number().nullable().optional(),
  target_food_cost_percentage: z.number().nullable().optional(),
  actual_food_cost_percentage: z.number().nullable().optional(),
  gross_margin: z.number().nullable().optional(),
  gross_margin_percentage: z.number().nullable().optional(),
  labor_cost_percentage: z.number().nullable().optional(),
  overhead_percentage: z.number().nullable().optional(),
  carbon_footprint: z.number().nullable().optional(),
  deduct_from_stock: z.boolean(),
  status: z.enum(Object.values(enum_recipe_status) as [string, ...string[]]),
  published_at: z.string().or(z.date()).nullable().optional(),
  archived_at: z.string().or(z.date()).nullable().optional(),
  tags: z.any().optional(),
  allergens: z.any().optional(),
  ingredients: z.any().optional(),
  preparation_steps: z.any().optional(),
  yield_variants: z.any().optional(),
  doc_version: z.number().optional(),
  audit: AuditSchema.optional(),
});
