import { z } from 'zod';
import { createZodDto } from 'nestjs-zod';
import { AuditSchema } from '@/common/dto/audit/audit.dto';

export const RecipeEquipmentCreate = z.object({
  code: z.string().min(1),
  name: z.string().min(1),
  description: z.string().nullable().optional(),
  category_id: z.string().uuid().nullable().optional(),
  brand: z.string().nullable().optional(),
  model: z.string().nullable().optional(),
  serial_no: z.string().nullable().optional(),
  capacity: z.string().nullable().optional(),
  power_rating: z.string().nullable().optional(),
  station: z.string().nullable().optional(),
  operation_instructions: z.string().nullable().optional(),
  safety_notes: z.string().nullable().optional(),
  cleaning_instructions: z.string().nullable().optional(),
  maintenance_schedule: z.string().nullable().optional(),
  last_maintenance_date: z.string().datetime().nullable().optional(),
  next_maintenance_date: z.string().datetime().nullable().optional(),
  note: z.string().nullable().optional(),
  is_active: z.boolean().default(true).optional(),
  is_portable: z.boolean().default(false).optional(),
  available_qty: z.number().int().optional(),
  total_qty: z.number().int().optional(),
  usage_count: z.number().int().optional(),
  average_usage_time: z.number().optional(),
  attachments: z.any().optional(),
  manuals_urls: z.any().optional(),
  info: z.any().nullable().optional(),
  dimension: z.any().nullable().optional(),
});

export type ICreateRecipeEquipment = z.infer<typeof RecipeEquipmentCreate>;
export class RecipeEquipmentCreateDto extends createZodDto(RecipeEquipmentCreate) {}

export const RecipeEquipmentUpdate = z.object({
  code: z.string().min(1).optional(),
  name: z.string().min(1).optional(),
  description: z.string().nullable().optional(),
  category_id: z.string().uuid().nullable().optional(),
  brand: z.string().nullable().optional(),
  model: z.string().nullable().optional(),
  serial_no: z.string().nullable().optional(),
  capacity: z.string().nullable().optional(),
  power_rating: z.string().nullable().optional(),
  station: z.string().nullable().optional(),
  operation_instructions: z.string().nullable().optional(),
  safety_notes: z.string().nullable().optional(),
  cleaning_instructions: z.string().nullable().optional(),
  maintenance_schedule: z.string().nullable().optional(),
  last_maintenance_date: z.string().datetime().nullable().optional(),
  next_maintenance_date: z.string().datetime().nullable().optional(),
  note: z.string().nullable().optional(),
  is_active: z.boolean().optional(),
  is_portable: z.boolean().optional(),
  available_qty: z.number().int().optional(),
  total_qty: z.number().int().optional(),
  usage_count: z.number().int().optional(),
  average_usage_time: z.number().optional(),
  attachments: z.any().optional(),
  manuals_urls: z.any().optional(),
  info: z.any().nullable().optional(),
  dimension: z.any().nullable().optional(),
});

export type IUpdateRecipeEquipment = z.infer<typeof RecipeEquipmentUpdate> & { id: string };
export class RecipeEquipmentUpdateDto extends createZodDto(RecipeEquipmentUpdate) {}

export const RecipeEquipmentResponseSchema = z.object({
  id: z.string().uuid(),
  code: z.string(),
  name: z.string(),
  description: z.string().nullable().optional(),
  category_id: z.string().uuid().nullable().optional(),
  category_name: z.string().nullable().optional(),
  category: z.object({
    id: z.string().uuid(),
    name: z.string(),
  }).nullable().optional(),
  brand: z.string().nullable().optional(),
  model: z.string().nullable().optional(),
  serial_no: z.string().nullable().optional(),
  capacity: z.string().nullable().optional(),
  power_rating: z.string().nullable().optional(),
  station: z.string().nullable().optional(),
  operation_instructions: z.string().nullable().optional(),
  safety_notes: z.string().nullable().optional(),
  cleaning_instructions: z.string().nullable().optional(),
  maintenance_schedule: z.string().nullable().optional(),
  last_maintenance_date: z.string().or(z.date()).nullable().optional(),
  next_maintenance_date: z.string().or(z.date()).nullable().optional(),
  note: z.string().nullable().optional(),
  is_active: z.boolean().nullable().optional(),
  is_portable: z.boolean().nullable().optional(),
  available_qty: z.number().nullable().optional(),
  total_qty: z.number().nullable().optional(),
  usage_count: z.number().nullable().optional(),
  average_usage_time: z.number().nullable().optional(),
  attachments: z.any().optional(),
  manuals_urls: z.any().optional(),
  info: z.any().nullable().optional(),
  dimension: z.any().nullable().optional(),
  doc_version: z.number().optional(),
  audit: AuditSchema.optional(),
});
